import Header from "@/components/header/header";
import type { Metadata } from "next";
import { Bree_Serif } from "next/font/google";
import "./globals.css";

const bree = Bree_Serif({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
  variable: "--font-bree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={bree.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
