import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <nav>
          <ul>
            <li>
              <Link href='/'>Home</Link>
            </li>
            <li>
              <Link href='/projects'>Projects</Link>
            </li>
            <li>
              <Link href='/about'>About</Link>
            </li>
            <li>
              <Link href='/blogs'>Blogs</Link>
              <ul>
                <li>
                  <Link href='/blogs/blog1'>First Blog</Link>
                </li>
                <li>
                  <Link href='/blogs/blog2'>Second Blog</Link>
                </li>
                <li>
                  <Link href='/blogs/blog3'>Third Blog</Link>
                </li>
              </ul>
            </li>
            <li>
              <Link href='/contact'>Contact Us</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
